name: BuildAndTest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    permissions:
        checks: write
        pull-requests: write
 
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore Feed/Feed.sln
    - name: Build
      run: dotnet build Feed/Feed.sln --no-restore
    - name: Start containers
      run: docker-compose -f Feed/docker-compose.yml up -d
 
    - name: Run tests
      run: dotnet test Feed.IntegrationTests/Feed.IntegrationTests.csproj --no-build --verbosity normal --logger "trx;LogFileName=xtests.trx"
 
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2      
      if: always()
      with:
        trx_files: "/home/runner/work/attrectoTrial/attrectoTrial/Feed.IntegrationTests/TestResults/xtests.trx"      
 
    - name: Stop containers
      if: always()
      run: docker-compose down
